# Generated by Django 5.2.7 on 2025-11-06 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='biografia',
        ),
        migrations.AlterField(
            model_name='servico',
            name='area_atendimento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria do serviço.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='prazo_estimado_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('preferencias', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.cliente'),
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('experiencia_anos', models.PositiveSmallIntegerField(default=0)),
                ('avaliacao_media', models.FloatField(default=0.0)),
                ('especialidades', models.ManyToManyField(blank=True, related_name='profissionais', to='core.categoria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contrato',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.profissional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='core.profissional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='profissional',
            field=models.ForeignKey(default=1, help_text='Profissional que oferece o serviço.', on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.profissional'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidade',
            unique_together={('profissional', 'data', 'inicio', 'fim')},
        ),
        migrations.RemoveField(
            model_name='disponibilidade',
            name='prestador',
        ),
    ]
