# Generated by Django 5.2.7 on 2025-11-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clienteproxy_profissionalproxy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='experiencia_anos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
