# Generated by Django 5.2.7 on 2025-11-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profissional_experiencia_anos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='papel_ativo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('profissional', 'Profissional')], default='cliente', help_text='Define qual papel o usuário está usando atualmente na interface.', max_length=20),
        ),
    ]
