# Generated by Django 5.2.7 on 2025-11-19 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_papel_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profissional',
            name='total_servicos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
