# Generated by Django 5.2.7 on 2025-11-20 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='avaliacao_media',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
